---
- name: Setup and deploy Docker container
  hosts: dynamic-host
  become: true
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Pull Docker image
      docker_image:
        name: sanjaykshebbar/asi-insurance-app
        tag: latest
        source: pull

    - name: Run Docker container
      docker_container:
        name: asi-insurance-app-container
        image: sanjaykshebbar/asi-insurance-app:latest
        state: started
        ports:
          - "80:80"

